// Safe IPC bridge exposed to the renderer as `window.api`.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getServers: () => ipcRenderer.invoke('servers:get'),
  saveServers: (servers) => ipcRenderer.invoke('servers:save', servers),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (s) => ipcRenderer.invoke('settings:save', s),
  testServer: (server) => ipcRenderer.invoke('server:test', server),
  openNyx: (name) => ipcRenderer.invoke('nyx:open', name),
  openAnonLog: (name) => ipcRenderer.invoke('anonlog:open', name),
  testAgentHttps: (name) => ipcRenderer.invoke('agent:httpsTest', name),
  openHtop: (name) => ipcRenderer.invoke('htop:open', name),
  readAnonrc: (name) => ipcRenderer.invoke('anonrc:read', name),
  writeAnonrc: (name, content, opts) => ipcRenderer.invoke('anonrc:write', name, content, opts),
  applyAnonrcPreset: (name) => ipcRenderer.invoke('anonrc:applyPreset', name),
  applyExitPorts: (exclude) => ipcRenderer.invoke('anonrc:applyExitPorts', exclude),
  firewallApplyExitPorts: (exclude) => ipcRenderer.invoke('firewall:applyExitPorts', exclude),
  getPublicIp: () => ipcRenderer.invoke('ip:public'),
  whitelistFail2ban: (nameOrAll, ipOverride) => ipcRenderer.invoke('fail2ban:whitelistAll', nameOrAll, ipOverride),
  securityScan: (nameOrAll) => ipcRenderer.invoke('security:scan', nameOrAll),
  securityHarden: (name) => ipcRenderer.invoke('security:harden', name),
  auditRelay: (name) => ipcRenderer.invoke('relay:audit', name),
  setupCheck: (name) => ipcRenderer.invoke('relay:setupCheck', name),
  bindRelayWallet: (name, wallet) => ipcRenderer.invoke('relay:bindWallet', name, wallet),
  fetchRelayRewards: (name, wallet) => ipcRenderer.invoke('relay:rewards', name, wallet),
  fetchRelayFingerprints: () => ipcRenderer.invoke('relay:fingerprints'),
  fetchRelayFamilyPlan: () => ipcRenderer.invoke('relay:familyPlan'),
  applyRelayFamilyAll: () => ipcRenderer.invoke('relay:familyApplyAll'),
  fetchFleetHealthRewards: () => ipcRenderer.invoke('relay:fleetHealthRewards'),
  getRewardHistory: () => ipcRenderer.invoke('rewardHistory:get'),
  appendRewardHistory: (payload) => ipcRenderer.invoke('rewardHistory:append', payload),
  fetchRelayFlags: () => ipcRenderer.invoke('relay:flags'),
  fetchAoRewardEstimates: () => ipcRenderer.invoke('relay:aoRewardEstimates'),
  fetchAoFingerprintRewards: (fingerprints, wallets) => ipcRenderer.invoke('relay:aoFingerprintRewards', fingerprints, wallets),
  fetchNetworkStats: () => ipcRenderer.invoke('network:stats'),
  fetchRelayNetworkStats: (fingerprints) => ipcRenderer.invoke('network:relayStats', fingerprints),
  openRewardsDashboard: () => ipcRenderer.invoke('dashboard:open'),
  fetchAnyonContractData: (wallet) => ipcRenderer.invoke('anyon:contractData', wallet),
  fetchAnyoneNews: () => ipcRenderer.invoke('news:get'),
  fetchAnyoneTokenPrice: () => ipcRenderer.invoke('market:tokenPrice'),
  testAlarm: () => ipcRenderer.invoke('alarm:test'),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  revealConfigFile: () => ipcRenderer.invoke('config:reveal'),
  activateLicense: (key) => ipcRenderer.invoke('license:activate', key),
  getLicenseStatus: () => ipcRenderer.invoke('license:status'),
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  clipboardReadText: () => ipcRenderer.invoke('clipboard:readText'),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard:writeText', text),
  editCut: () => ipcRenderer.invoke('edit:cut'),
  editCopy: () => ipcRenderer.invoke('edit:copy'),
  editPaste: () => ipcRenderer.invoke('edit:paste'),
  editSelectAll: () => ipcRenderer.invoke('edit:selectAll'),
  showEditContextMenu: () => ipcRenderer.invoke('edit:showContextMenu'),

  onSnapshot: (cb) => ipcRenderer.on('snapshot', (_e, data) => cb(data)),
  onAutoFixResult: (cb) => ipcRenderer.on('autofix-result', (_e, data) => cb(data)),
  onAutoFixLog: (cb) => ipcRenderer.on('autofix-log', (_e, data) => cb(data)),
  onAutoFixToggle: (cb) => ipcRenderer.on('autofix-toggle', (_e, data) => cb(data)),
  onWindowVisibility: (cb) => ipcRenderer.on('window-visibility', (_e, data) => cb(data)),
  onFocusRelay: (cb) => ipcRenderer.on('focus-relay', (_e, name) => cb(name)),
  onWebviewRewardUrl: (cb) => ipcRenderer.on('webview-reward-url', (_e, data) => cb(data)),

  getAutoFixSettings: () => ipcRenderer.invoke('autofix:getSettings'),
  saveAutoFixSettings: (s) => ipcRenderer.invoke('autofix:saveSettings', s),
  testAutoFix: (s) => ipcRenderer.invoke('autofix:test', s),

  installAgent: (name) => ipcRenderer.invoke('agent:install', name),
  installAgentAll: () => ipcRenderer.invoke('agent:installAll'),
  removeAgent: (name) => ipcRenderer.invoke('agent:remove', name),
  startMonitor: (mode) => ipcRenderer.invoke('monitor:start', mode),
  hideWindow: () => ipcRenderer.send('window:hide'),
  quit: () => ipcRenderer.send('window:quit'),
  setZoom: (factor) => { try { require('electron').webFrame.setZoomFactor(factor); } catch {} },
  getZoom: () => { try { return require('electron').webFrame.getZoomFactor(); } catch { return 1; } },
});
